version: '3.7'

services:
  shortener:
    build:
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - MONGO_HOST=mongodb
      - ETCD_ENDPOINTS=http://etcd:2379
      - REDIS_DSN=redis:6379
    depends_on:
      - mongodb
      - etcd
      - redis

  etcd:
    image: 'bitnami/etcd:latest'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://127.0.0.1:2379
    ports:
      - 2379:2379
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
  redis:
    image: redis:alpine
    command: redis-server --bind redis --requirepass admin --maxmemory 256mb --maxmemory-policy allkeys-lfu
    ports:
      - 6379:6379

